name: Sample
favicon: null
layout_spectrum: 0.87902
typography_spectrum: 0.16951533849351108
title: My Title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c8b9c'
    - '#8bbdc4'
    - '#50a8b2'
    - '#dceaf5'
    - '#126a80'
  brandStrength: 0.5
  lightness: 0.8473072182387114
  saturation: 0.23114014766179025
  rhythmicContrast: 0.3023160370066762
purpose: []
