name: Sample
favicon: null
layout_spectrum: 0.9293243505526334
typography_spectrum: 0.16951533849351108
title: My Title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6e4ec'
    - '#afb5b3'
    - '#7d564d'
    - '#c1892c'
    - '#2f3231'
  brandStrength: 0.5
  lightness: 0.8473072182387114
  saturation: 0.23114014766179025
  rhythmicContrast: 0.3023160370066762
purpose: []
