name: Sample
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74232
title: My Title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c8b9c'
    - '#8bbdc4'
    - '#50a8b2'
    - '#dceaf5'
    - '#126a80'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
